{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите название искомой вакансии (если название состоит из нескольких слов, вместо пробелов наберите знак \"+\"):    python\n",
      "Введите количество страниц, которые хотите проанализировать:    2\n",
      "https://spb.hh.ru/search/vacancy?L_is_autosearch=false&clusters=true&enable_snippets=true&search_period=3&text=python&page=0\n",
      "https://spb.hh.ru/search/vacancy?L_is_autosearch=false&clusters=true&enable_snippets=true&search_period=3&text=python&page=1\n",
      "{'page0': [{'link': 'https://spb.hh.ru/vacancy/35434044?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Программист Python (в Ригу)'},\n",
      "           {'valute': 'EUR'},\n",
      "           {'maximal salary': '3000', 'minimal salary': '2000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35173848?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Senior Python Developer (to Riga)'},\n",
      "           {'valute': 'EUR'},\n",
      "           {'maximal salary': '4500', 'minimal salary': '3000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35110195?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Стажер-программист Python'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35436560?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Разработчик Python'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/34733084?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Разработчик Python'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '130000'}],\n",
      " 'page1': [{'link': 'https://spb.hh.ru/vacancy/35199079?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Full-Stack Python developer'},\n",
      "           {'valute': 'USD'},\n",
      "           {'maximal salary': '4000', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35310681?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python-разработчик'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '110000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35300706?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Разработчик Python'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': '90000', 'minimal salary': '60000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/33522088?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python Developer/Analyst'},\n",
      "           {'valute': 'USD'},\n",
      "           {'maximal salary': '3000', 'minimal salary': '1200'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35431519?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Стажёр (Анализ данных, data science)'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35503487?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python-разработчик'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': '200000', 'minimal salary': '140000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/34079847?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python Developer'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35075027?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python разработчик'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '90000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35189679?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Младший программист Python'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35415967?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Senior Python разработчик (GO)'},\n",
      "           {'valute': 'EUR'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '3000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35296762?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python Data Scientist'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '150000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35185236?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Разработчик Python/Django в Сочи'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '100000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35185238?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Разработчик Python/Django в Сочи'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '100000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35113433?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python разработчик'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '120000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35196412?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python developer'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': '200000', 'minimal salary': '150000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35380437?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Machine Learning Developer (AWS)'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '320000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35305845?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Python developer'},\n",
      "           {'valute': 'EUR'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '1500'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35185237?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Разработчик Python/Django в Сочи'},\n",
      "           {'valute': 'руб'},\n",
      "           {'maximal salary': 'unknown', 'minimal salary': '100000'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35395690?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Backend Python Developer'},\n",
      "           {'valute': 'None'},\n",
      "           {'maximal salary': '750000', 'minimal salary': 'unknown'},\n",
      "           {'link': 'https://spb.hh.ru/vacancy/35168856?query=python',\n",
      "            'site': 'spb.hh.ru',\n",
      "            'title': 'Специалист по разработке full stack (python)'},\n",
      "           {'valute': 'None'},\n",
      "           {'maximal salary': '650000', 'minimal salary': '600000'}]}\n"
     ]
    }
   ],
   "source": [
    "from bs4 import BeautifulSoup as bs\n",
    "import requests\n",
    "from pprint import pprint\n",
    "import re\n",
    "import urllib\n",
    "\n",
    "head = {'accept': '*/*', \n",
    "          'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',\n",
    "          }\n",
    "name = str(input('Введите название искомой вакансии (если название состоит из нескольких слов, вместо пробелов наберите знак \"+\"):    '))\n",
    "page = str(input('Введите количество страниц, которые хотите проанализировать:    '))\n",
    "\n",
    "url = 'https://spb.hh.ru/search/vacancy?L_is_autosearch=false&clusters=true&enable_snippets=true&search_period=3&text='+name+'&page='\n",
    "    \n",
    "def hh_parse(base_url, headers):\n",
    "    vacancies = []\n",
    "    session = requests.Session()\n",
    "    req = session.get(base_url, headers = head)\n",
    "    if req.status_code == 200:\n",
    "        bscontent = bs(req.content, 'lxml')\n",
    "        divs = bscontent.find_all('div', attrs = {'data-qa':'vacancy-serp__vacancy'})\n",
    "        #print(len(divs))\n",
    "        for div in divs:\n",
    "            title = div.find('a', attrs = {'data-qa': 'vacancy-serp__vacancy-title'}).text\n",
    "            href = div.find('a', attrs = {'data-qa': 'vacancy-serp__vacancy-title'})['href']\n",
    "            site = urllib.parse.urlsplit(href).netloc\n",
    "            vacancies.append({\n",
    "                'title': title,\n",
    "                'link': href,\n",
    "                'site': site\n",
    "            })\n",
    "            if div.find('div', attrs = {'data-qa': 'vacancy-serp__vacancy-compensation'}) != None:\n",
    "                sal = div.find('div', attrs = {'data-qa': 'vacancy-serp__vacancy-compensation'}).text\n",
    "                sal = re.sub('[\\\\s]+', '', sal)\n",
    "                #print(sal)\n",
    "                val_list = ['руб', 'EUR', 'USD', 'RUB']\n",
    "                val = re.findall(r\"(?=(\"+'|'.join(val_list)+r\"))\", sal)\n",
    "                if not val:\n",
    "                    vacancies.append({'valute': 'None'})\n",
    "                else:\n",
    "                    vacancies.append({'valute': val[0]})\n",
    "                #re.sub('[\\\\ха]+', '', salary)\n",
    "                p = re.compile('^(от|до)')\n",
    "                pp = re.compile('^\\d')\n",
    "                d = re.compile('[\\d]+')\n",
    "                if pp.match(sal):\n",
    "                    nums = re.findall(d, sal)\n",
    "                    min_salary = nums[0]\n",
    "                    max_salary = nums[1]\n",
    "                    vacancies.append({\n",
    "                        'minimal salary': min_salary,\n",
    "                        'maximal salary': max_salary,\n",
    "                        #'valute': val[0]\n",
    "                    })\n",
    "                elif p.match(sal):\n",
    "                    po = re.compile('^[от]')\n",
    "                    pd = re.compile('^[до]')\n",
    "                    fromf = po.match(sal)\n",
    "                    upto = pd.match(sal)\n",
    "                    if fromf:\n",
    "                        digit = re.search(d, sal)\n",
    "                        min_salary = sal[digit.start():digit.end()]\n",
    "                        vacancies.append({\n",
    "                            'maximal salary': 'unknown',\n",
    "                            'minimal salary': min_salary,\n",
    "                            #'valute': val[0]\n",
    "                        })\n",
    "                    elif upto:\n",
    "                        digit = re.search(d, sal)\n",
    "                        max_salary = sal[digit.start():digit.end()]\n",
    "                        vacancies.append({\n",
    "                            'minimal salary': 'unknown',\n",
    "                            'maximal salary': max_salary,\n",
    "                            #'valute': val[0]\n",
    "                        })\n",
    "                # разделитель в больших числах  /\\d{1,3}(?=(\\d{3})+(?!\\d))/g \n",
    "            else:\n",
    "                sal = 'unknown'\n",
    "                vacancies.append({\n",
    "                    'minimal salary': sal,\n",
    "                    'maximal salary': sal,\n",
    "                    #'valute': 'None'\n",
    "                })\n",
    "\n",
    "            #pprint(vacancies)\n",
    "    else:\n",
    "        print('error')\n",
    "    return vacancies\n",
    "\n",
    "vac = dict()\n",
    "\n",
    "for i in range(int(page)):\n",
    "    base_url = url+str(i)\n",
    "    print(base_url)\n",
    "    key = 'page'+str(i)\n",
    "    vac[key] = hh_parse(base_url, head)\n",
    "    #vac = hh_parse(base_url, head)\n",
    "    #pprint(vac)\n",
    "    #pprint('   ')\n",
    "\n",
    "pprint(vac)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
